# Generated by Django 5.2.3 on 2025-06-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_customuser_referred_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="referral_points",
            field=models.IntegerField(default=0),
        ),
    ]
